# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

# Flexbox Layout Manager Used By React Native
pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga/Yoga.podspec'

# React Native
pod 'React', path: '../node_modules/react-native', subspecs: [
  # Comment out any unneeded subspecs to reduce bundle size.
  'Core',
  'DevSupport',
  'RCTActionSheet',
  'RCTAnimation',
  'RCTBlob',
  'RCTCameraRoll',
  'RCTGeolocation',
  'RCTImage',
  'RCTNetwork',
  'RCTPushNotification',
  'RCTSettings',
  'RCTText',
  'RCTVibration',
  'RCTWebSocket',
  'RCTLinkingIOS'
]

# Mapbox
pod 'react-native-mapbox-gl', :path => '../node_modules/@react-native-mapbox-gl/maps'

# Third party
pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

post_install do |installer|
  installer.pods_project.targets.each do |target|
    targets_to_ignore = %w(React yoga)
    if targets_to_ignore.include? target.name
      target.remove_from_project
    end
    if target.name == "React"
      target.remove_from_project
    end
  end
end



target 'buckitapp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for buckitapp

  target 'buckitapp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'buckitappTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'buckitapp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for buckitapp-tvOS

end
