# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'buckitapp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for buckitapp

  target 'buckitapp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'buckitappTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'buckitapp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for buckitapp-tvOS

  target 'buckitapp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
